/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menubar.java
 *
 * Created on 4 Sep, 2018, 6:39:14 PM
 */

/**
 *
 * @author My
 */
public class Menubar extends javax.swing.JFrame {

    /** Creates new form Menubar */
    public Menubar() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        DonoLogin = new javax.swing.JButton();
        DonorRegistration = new javax.swing.JButton();
        SearchBlood = new javax.swing.JButton();
        AdminLogin = new javax.swing.JButton();
        PatientRegistration = new javax.swing.JButton();
        Appontment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255)), "WELCOME TO HOME PAGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 204, 204))); // NOI18N

        DonoLogin.setBackground(new java.awt.Color(255, 255, 255));
        DonoLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DonoLogin.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\CUSTOM_ICON_c88a9790-84ef-4cfb-8692-886124f82884.png")); // NOI18N
        DonoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonoLoginActionPerformed(evt);
            }
        });
        DonoLogin.setBounds(240, 160, 120, 120);
        jDesktopPane1.add(DonoLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DonorRegistration.setBackground(new java.awt.Color(255, 255, 255));
        DonorRegistration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DonorRegistration.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\icons8_Registration_96px_1.png")); // NOI18N
        DonorRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonorRegistrationActionPerformed(evt);
            }
        });
        DonorRegistration.setBounds(70, 340, 130, 110);
        jDesktopPane1.add(DonorRegistration, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SearchBlood.setBackground(new java.awt.Color(255, 255, 255));
        SearchBlood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchBlood.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\BloodSearchIcon.gif")); // NOI18N
        SearchBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBloodActionPerformed(evt);
            }
        });
        SearchBlood.setBounds(390, 160, 120, 120);
        jDesktopPane1.add(SearchBlood, javax.swing.JLayeredPane.DEFAULT_LAYER);

        AdminLogin.setBackground(new java.awt.Color(255, 255, 255));
        AdminLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AdminLogin.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\AdminIcon4.png")); // NOI18N
        AdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginActionPerformed(evt);
            }
        });
        AdminLogin.setBounds(70, 160, 120, 120);
        jDesktopPane1.add(AdminLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PatientRegistration.setBackground(new java.awt.Color(255, 255, 255));
        PatientRegistration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PatientRegistration.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\icons8_Registration_96px_1.png")); // NOI18N
        PatientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientRegistrationActionPerformed(evt);
            }
        });
        PatientRegistration.setBounds(240, 340, 120, 110);
        jDesktopPane1.add(PatientRegistration, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Appontment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Appontment.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\add-event-icon.png")); // NOI18N
        Appontment.setBounds(400, 340, 110, 110);
        jDesktopPane1.add(Appontment, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Search");
        jLabel1.setBounds(420, 280, 80, 30);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Donor Registration");
        jLabel4.setBounds(70, 450, 140, 20);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Patient Registration");
        jLabel5.setBounds(240, 450, 140, 20);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("WELCOME TO SMART HUMAN BLOOD BANK");
        jLabel6.setBounds(20, 50, 530, 50);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\mca documents\\Icon\\hospital.png")); // NOI18N
        jLabel7.setBounds(240, 100, 30, 40);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("Appointment");
        jLabel8.setBounds(410, 450, 100, 20);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Admin Login");
        jLabel2.setBounds(90, 280, 100, 30);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Donor Login");
        jLabel3.setBounds(260, 280, 100, 30);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DonoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonoLoginActionPerformed
      setVisible(false);
        DonorLogin lb=new DonorLogin();
       lb.setVisible(true);
    }//GEN-LAST:event_DonoLoginActionPerformed

    private void DonorRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonorRegistrationActionPerformed
       setVisible(false);
        DonorRegistration pa=new DonorRegistration();
       pa.setVisible(true);
    }//GEN-LAST:event_DonorRegistrationActionPerformed

    private void SearchBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBloodActionPerformed
        setVisible(false);
        DonorsTable jb=new DonorsTable();
        jb.getdata();
        //setVisible(false);
        //jb.setVisible(true);
    }//GEN-LAST:event_SearchBloodActionPerformed

    private void PatientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRegistrationActionPerformed
        setVisible(false);
        PatientReg pt=new PatientReg();
        pt.setVisible(true);
    }//GEN-LAST:event_PatientRegistrationActionPerformed

    private void AdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginActionPerformed
         setVisible(false);
         AdminLogin adln=new AdminLogin();
         adln.setVisible(true);
    }//GEN-LAST:event_AdminLoginActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menubar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLogin;
    private javax.swing.JButton Appontment;
    private javax.swing.JButton DonoLogin;
    private javax.swing.JButton DonorRegistration;
    private javax.swing.JButton PatientRegistration;
    private javax.swing.JButton SearchBlood;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables

}
